addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "$scalafmt_version$")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.10.0")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "$sbtNativePackager_version$")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "$scalajs_version$")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "$scalajs_cross_version$")
